spring.application.name=wealth-portfolio-api
server.port=8010

# Security - set to false to disable token validation during development
security.auth.enabled=false

# Keycloak - OAuth2 Resource Server
spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8080/realms/myrealm

# Claude API
claude.api.key=${ANTHROPIC_API_KEY}
claude.api.url=https://api.anthropic.com/v1/messages

# Finnhub API
finnhub.api.key=${FINNHUB_API_KEY}
